name: IssueOps - Ada Automations

on:
  issue_comment:
    types: [created]

jobs:
  ada-issueops:
    if: github.event.comment.body startsWith '/'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
         pip install -r requirements.txt

      - name: Parse and run commands
        run: |
          echo "Command: ${{ github.event.comment.body }}"

          if [[ "${{ github.event.comment.body }}" == "/setup-ada" ]]; then
            echo "Running Ada setup..."
            python installer.py --repair

          elif [[ "${{ github.event.comment.body }}" == "/run-ada" ]]; then
            echo "Starting Ada via daemon..."
            nohup python daemon.py &

          elif [[ "${{ github.event.comment.body }}" == "/check-config" ]]; then
            echo "Printing config/settings.yaml..."
            cat config/settings.yaml

          else
            echo "Unrecognized command."

      - name: Comment status back on issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Ada has processed the command: `${{ github.event.comment.body }}`

            If this command included setup or daemon tasks, the logs are available in this workflow run.

            *Powered by IssueOps.
         
            

            
